from django.db import models


class Player(models.Model):
    seas_id = models.IntegerField()
    season = models.IntegerField()
    player_id = models.IntegerField()
    name = models.CharField(max_length=100)
    birth_year = models.IntegerField(null=True, blank=True)
    pos = models.CharField(max_length=100)
    age = models.IntegerField(null=True, blank=True)
    experience = models.IntegerField(null=True, blank=True)
    lg = models.CharField(max_length=100)
    tm = models.CharField(max_length=100)
    g = models.IntegerField(null=True, blank=True)
    gs = models.IntegerField(null=True, blank=True)
    mp_per_game = models.FloatField(null=True, blank=True)
    fg_per_game = models.FloatField(null=True, blank=True)
    fga_per_game = models.FloatField(null=True, blank=True)
    fg_percent = models.FloatField(null=True, blank=True)
    x3p_per_game = models.FloatField(null=True, blank=True)
    x3pa_per_game = models.FloatField(null=True, blank=True)
    x3p_percent = models.FloatField(null=True, blank=True)
    x2p_per_game = models.FloatField(null=True, blank=True)
    x2pa_per_game = models.FloatField(null=True, blank=True)
    x2p_percent = models.FloatField(null=True, blank=True)
    e_fg_percent = models.FloatField(null=True, blank=True)
    ft_per_game = models.FloatField(null=True, blank=True)
    fta_per_game = models.FloatField(null=True, blank=True)
    ft_percent = models.FloatField(null=True, blank=True)
    orb_per_game = models.FloatField(null=True, blank=True)
    drb_per_game = models.FloatField(null=True, blank=True)
    trb_per_game = models.FloatField(null=True, blank=True)
    ast_per_game = models.FloatField(null=True, blank=True)
    stl_per_game = models.FloatField(null=True, blank=True)
    blk_per_game = models.FloatField(null=True, blank=True)
    tov_per_game = models.FloatField(null=True, blank=True)
    pf_per_game = models.FloatField(null=True, blank=True)
    pts_per_game = models.FloatField(null=True, blank=True)

    label = models.IntegerField(null=True, blank=True)


class Team(models.Model):
    season = models.IntegerField()
    lg = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    abbreviation = models.CharField(max_length=10)
    playoffs = models.BooleanField()
    g = models.IntegerField(null=True, blank=True)
    mp_per_game = models.FloatField(null=True, blank=True)
    fg_per_game = models.FloatField(null=True, blank=True)
    fga_per_game = models.FloatField(null=True, blank=True)
    fg_percent = models.FloatField(null=True, blank=True)
    x3p_per_game = models.FloatField(null=True, blank=True)
    x3pa_per_game = models.FloatField(null=True, blank=True)
    x3p_percent = models.FloatField(null=True, blank=True)
    x2p_per_game = models.FloatField(null=True, blank=True)
    x2pa_per_game = models.FloatField(null=True, blank=True)
    x2p_percent = models.FloatField(null=True, blank=True)
    ft_per_game = models.FloatField(null=True, blank=True)
    fta_per_game = models.FloatField(null=True, blank=True)
    ft_percent = models.FloatField(null=True, blank=True)
    orb_per_game = models.FloatField(null=True, blank=True)
    drb_per_game = models.FloatField(null=True, blank=True)
    trb_per_game = models.FloatField(null=True, blank=True)
    ast_per_game = models.FloatField(null=True, blank=True)
    stl_per_game = models.FloatField(null=True, blank=True)
    blk_per_game = models.FloatField(null=True, blank=True)
    tov_per_game = models.FloatField(null=True, blank=True)
    pf_per_game = models.FloatField(null=True, blank=True)
    pts_per_game = models.FloatField(null=True, blank=True)


class Game(models.Model):
    visit_team = models.CharField(max_length=100)
    home_team = models.CharField(max_length=100)
    visit_win = models.FloatField()
    home_win = models.FloatField()
    pred_model = models.CharField(max_length=100)


class Label(models.Model):
    v0 = models.FloatField()
    v1 = models.FloatField()
    label = models.IntegerField()
    name = models.CharField(max_length=100)
    pos = models.CharField(max_length=100)
