# Generated by Django 3.0.8 on 2021-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seas_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(null=True)),
                ('pos', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('lg', models.CharField(max_length=100)),
                ('tm', models.CharField(max_length=100)),
                ('g', models.IntegerField(null=True)),
                ('gs', models.IntegerField(null=True)),
                ('mp_per_game', models.FloatField(null=True)),
                ('fg_per_game', models.FloatField(null=True)),
                ('fga_per_game', models.FloatField(null=True)),
                ('fg_percent', models.FloatField(null=True)),
                ('x3p_per_game', models.FloatField(null=True)),
                ('x3pa_per_game', models.FloatField(null=True)),
                ('x3p_percent', models.FloatField(null=True)),
                ('x2p_per_game', models.FloatField(null=True)),
                ('x2pa_per_game', models.FloatField(null=True)),
                ('x2p_percent', models.FloatField(null=True)),
                ('e_fg_percent', models.FloatField(null=True)),
                ('ft_per_game', models.FloatField(null=True)),
                ('fta_per_game', models.FloatField(null=True)),
                ('ft_percent', models.FloatField(null=True)),
                ('orb_per_game', models.FloatField(null=True)),
                ('drb_per_game', models.FloatField(null=True)),
                ('trb_per_game', models.FloatField(null=True)),
                ('ast_per_game', models.FloatField(null=True)),
                ('stl_per_game', models.FloatField(null=True)),
                ('blk_per_game', models.FloatField(null=True)),
                ('tov_per_game', models.FloatField(null=True)),
                ('pf_per_game', models.FloatField(null=True)),
                ('pts_per_game', models.FloatField(null=True)),
            ],
        ),
    ]
