# Generated by Django 3.0.8 on 2021-11-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('lg', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10)),
                ('playoffs', models.BooleanField()),
                ('g', models.IntegerField(null=True)),
                ('mp_per_game', models.FloatField(null=True)),
                ('fg_per_game', models.FloatField(null=True)),
                ('fga_per_game', models.FloatField(null=True)),
                ('fg_percent', models.FloatField(null=True)),
                ('x3p_per_game', models.FloatField(null=True)),
                ('x3pa_per_game', models.FloatField(null=True)),
                ('x3p_percent', models.FloatField(null=True)),
                ('x2p_per_game', models.FloatField(null=True)),
                ('x2pa_per_game', models.FloatField(null=True)),
                ('x2p_percent', models.FloatField(null=True)),
                ('ft_per_game', models.FloatField(null=True)),
                ('fta_per_game', models.FloatField(null=True)),
                ('ft_percent', models.FloatField(null=True)),
                ('orb_per_game', models.FloatField(null=True)),
                ('drb_per_game', models.FloatField(null=True)),
                ('trb_per_game', models.FloatField(null=True)),
                ('ast_per_game', models.FloatField(null=True)),
                ('stl_per_game', models.FloatField(null=True)),
                ('blk_per_game', models.FloatField(null=True)),
                ('tov_per_game', models.FloatField(null=True)),
                ('pf_per_game', models.FloatField(null=True)),
                ('pts_per_game', models.FloatField(null=True)),
            ],
        ),
    ]
