# Generated by Django 3.0.8 on 2021-11-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ast_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='blk_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='drb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='e_fg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fg_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fga_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ft_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ft_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='fta_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mp_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='orb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pf_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='stl_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='tov_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='trb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x2p_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x2p_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x2pa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x3p_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x3p_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='x3pa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ast_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='blk_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='drb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fg_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fg_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fga_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ft_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='ft_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='fta_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='mp_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='orb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='pf_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='pts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stl_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='tov_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='trb_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x2p_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x2p_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x2pa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x3p_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x3p_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='x3pa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
