# Generated by Django 3.0.8 on 2021-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
