# Generated by Django 3.0.8 on 2021-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v0', models.FloatField()),
                ('v1', models.FloatField()),
                ('label', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
            ],
        ),
    ]
